### ISSUE TITLE
Task 2: Send an email to my Email

### ISSUE THREAD

**Issue by yinsang** [yinsang/littleSisterLearnCS#2]

**Comment by yinsang** [comment]
我收到了我自己从QQ邮箱发到gmail的邮件，没有收到你的。加油，再接再厉。

**Comment by weiyinzhen** [comment]
好的👌

**Comment by weiyinzhen** [comment]
don't know if I have successfully sent you an email. In GitHub, if you receive it, please reply me an email or let me know on wechat. Thank you

**Comment by yinsang** [comment]
> don't know if I have successfully sent you an email. In GitHub, if you receive it, please reply me an email or let me know on wechat. Thank you
I had send a new email to your QQ mail.

**Comment by weiyinzhen** [comment]
我已经收到了这个邮件，就是不知道你能不能收到我回复的邮件，我已经给你回复了。记得吃午饭。



发自我的iPhone


------------------ Original ------------------
From: 銀桑 ***@***.***&gt;
Date: Thu,Mar 11,2021 11:14 AM
To: yinsang/littleSisterLearnCS ***@***.***&gt;
Cc: weiyinzhen ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [yinsang/littleSisterLearnCS] Task 2: Send an email to my Email (#2)





  
don't know if I have successfully sent you an email. In GitHub, if you receive it, please reply me an email or let me know on wechat. Thank you
 I had send a new email to your QQ mail.

**Comment by yinsang** [comment]
Congratulations
