### ISSUE TITLE
Task 4: Raise an issue in this repository， just for Thanks is ok

### ISSUE THREAD

**Issue by yinsang** [yinsang/littleSisterLearnCS#4]
Price ¥2

**Comment by weiyinzhen** [comment]
I don't know when the rain will stop outside? Did it rain for you? Thank you all

**Comment by yinsang** [comment]
> I don't know when the rain will stop outside? Did it rain for you? Thank you all

No, it's cloudy here. 
You need raise an issue, not a comment, : )

**Comment by yinsang** [comment]
Congratulations
