### ISSUE TITLE
Task 5: create a repository named myFirstRepository in your account

### ISSUE THREAD

**Issue by yinsang** [yinsang/littleSisterLearnCS#5]
price 5

**Comment by weiyinzhen** [comment]
已经完成了。
![ACF5E95F-24BA-4043-BA26-C07D8E625B20](https://user-images.githubusercontent.com/80435093/110737361-33129e80-8268-11eb-8264-8aebfedac1f8.png)

**Comment by yinsang** [comment]
Congratulations
